'use client'
import { Inter } from "next/font/google";
import { QueryClient, QueryClientProvider } from "react-query";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = new QueryClient()
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <QueryClientProvider client={client} >

          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
